= Algorithms
:toc: left
:toclevels: 8
:stem:
// Access this file locally: file:///D:/Work/crazoter.github.io/algorithms.adoc
== Sorting


== Array Traversal
=== Unsorted
==== Find kth rank item
===== T:O(lg n), S:O(1): Quickselect
==== Find element repeated more than n/2 times
===== T:O(n), S:O(1): Counter + Number
----
int ctr, num = 0;
fori A[]:
  if ctr == 0:
    num = A[i];
  if num == A[i]: ctr++;
  else: ctr--;
return num;
// src: https://stackoverflow.com/questions/7059780/find-the-element-repeated-more-than-n-2-times
----

==== Maximum subarray Problem
===== T:O(n), S:O(1): Current & Max Sum
----
// Kadane's algorithm
// Modify w/ if statements to record subarray A[a, b]
int best_sum = 0, curr_sum = 0;
fori A[]:
  curr_sum = max(0, curr_sum + A[i]);
  best_sum = max(best_sum, curr_sum);
return best_sum;
// src: https://en.wikipedia.org/wiki/Maximum_subarray_problem
----

==== Find min / max item
===== T:O(n), S:O(1): Linear search

=== Sorted
==== Find kth rank item
===== T:O(1), S:O(1): Lookup

=== Misc
==== Find k shifts (to the right) of sorted array
===== T:O(nlgn), S:O(1): Find 1st inversion with mergesort
===== T:O(lgn), S:O(1): Find 1st inversion with binary search (Untested)
----
int L = 0, R = A.len - 1, k = 0;
while (R >= L): // While Search space > 0
  int mid = (R - L) / 2;
  if (A[mid] < A[0]):
    if (mid < k): 
      k = mid;
    R = mid - 1; // Trim Right if mid val 
  else:
    L = mid + 1; // Trim Left 
return k;
----

== Directed Graph / Linked List
=== Find Cycle (& start node)
==== T:O(n), S:O(1): p=->next, q=->->next
Ptrs p, q. Start at head. p=->next, q=->next->next. Loop found when p=q, end when q=null (Floyd's Tortoise & Hare).

Find start node: q = head. p=->next, q=->next. end when p=q. 

==== T:O(n), S:O(n): Hashset
Check collision. Start node = collision.

=== Get Cycle size
==== T:O(n), S:O(1): Find pt in loop, use 2nd ptr to iterate
Ptrs p, q. Find point in loop (See loop detection). q=->next, ctr++, stop if p=q.

== Union Find Disjoint Set (Amortized O(stem:[\alpha](n)) ~= O(1))
==== MakeSet(x)
----
if x is not present:
  add x to the tree
  x.parent <- x
  x.rank <- 0 // rank refers to height
  x.size <- 1
----
==== Find(x) (with path reduction)
----
// 3 Options:
// Path Compression (recurse path, make node point to its root)
// Recall that if x.parent == x, x is the root. 
if x.parent != x: // If current node is not the root, recurse
  x.parent <- find(x.parent)
return x.parent

// Path Halving (Make every even/odd node point to its grandparent)
while x.parent != x:
  x.parent <- x.parent.parent // parent is now grandparent
  x <- x.parent // move to grandparent
return x

// Path Splitting (Make every node point to its grandparent)
while x.parent != x:
  next <- x.parent
  x.parent <- next.parent
  x <- next
return x
----
==== Union(x, y)
----
// By rank or size: Merge smaller subtree into larger subtree
rootOfX <- find(x)
rootOfY <- find(y)
return if rootOfX == rootOfY

// Ensure rootOfX is always of equal/higher rank
else if [rank:(rootOfX.rank < rootOfY.rank)] [size:(rootOfX.size < rootOfY.size)]
  swap rootOfX and rootOfY

rootOfY.parent <- rootOfX // Merge rootOfY into rootOfX
[rank:
if rootOfX.rank == rootOfY.rank // If they have the same rank, increment rank of root by 1
  rootOfX.rank += 1
]
[size: rootOfX.size += rootOfY.size]
----

== Divide & Conquer
=== Closest Pair of Euclidean Points
1. Sort points by x-coordinate.
2. Split the points into two equal-sized subsets by median point.
3. Solve the two subsets recursively. This results in left-side and right-side minimum distances dLmin and dRmin.
4. Find the minimal distance dLRmin among the set of pairs of points in which one point lies on the left of the dividing vertical and the other point lies to the right.
. Observation shows smallest distance, d, must be stem:[\leq] min{dLMin, dRmin}.
. for each point pLeft in the left subset, take points in the right subset, pRight, that lie in the rectangle of dimensions (d, 2 ⋅ d) in the right subset and calculate dLRmin = min{dist(pLeft, pRight), d}
5. Return min{dLmin, dRmin, dLRmin}.


Working:

stem:[{distance}_{eggs}(trials)]

stem:[t\geq 2: d_n(t) = 1 + d_{n-1}(t-1) + d_n(t-1)]

stem:[t\geq 1: d_1(t) = 1]

stem:[t\geq 1: d_2(t) = t(t+1)/2]

stem:[t \lt n: d_n(t) = d_t(t)]